# Generated by Django 5.1.1 on 2024-10-05 20:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primaryStreet_1', models.CharField(blank=True, max_length=150, null=True)),
                ('primaryStreet_2', models.CharField(blank=True, max_length=150, null=True)),
                ('primaryCity', models.CharField(blank=True, max_length=100, null=True)),
                ('primaryState', models.CharField(blank=True, max_length=100, null=True)),
                ('primaryCountry', models.CharField(blank=True, max_length=100, null=True)),
                ('primaryPostalCode', models.CharField(blank=True, max_length=7, null=True)),
                ('mailingStreet_1', models.CharField(blank=True, max_length=150, null=True)),
                ('mailingStreet_2', models.CharField(blank=True, max_length=150, null=True)),
                ('mailingCity', models.CharField(blank=True, max_length=100, null=True)),
                ('mailingState', models.CharField(blank=True, max_length=100, null=True)),
                ('mailingCountry', models.CharField(blank=True, max_length=100, null=True)),
                ('mailingPostalCode', models.CharField(blank=True, max_length=7, null=True)),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('phoneNumber', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+1 (XXX) XXX-XXXX", regex='^\\+?1?\\d{9,13}$')])),
                ('personalEmail', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilePhoto', models.ImageField(blank=True, null=True, upload_to='')),
                ('dateOfBirth', models.DateField(blank=True, null=True)),
                ('socialSecurity', models.CharField(blank=True, max_length=5, null=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identity', to='smarteq.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primaryStreet_1', models.CharField(blank=True, max_length=150, null=True)),
                ('primaryStreet_2', models.CharField(blank=True, max_length=150, null=True)),
                ('primaryCity', models.CharField(blank=True, max_length=100, null=True)),
                ('primaryState', models.CharField(blank=True, max_length=100, null=True)),
                ('primaryCountry', models.CharField(blank=True, max_length=100, null=True)),
                ('primaryPostalCode', models.CharField(blank=True, max_length=7, null=True)),
                ('schoolName', models.CharField(max_length=255)),
                ('major', models.CharField(max_length=255)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education', to='smarteq.identity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officeStreet_1', models.CharField(blank=True, max_length=150, null=True)),
                ('officeStreet_2', models.CharField(blank=True, max_length=150, null=True)),
                ('officeCity', models.CharField(blank=True, max_length=100, null=True)),
                ('officeState', models.CharField(blank=True, max_length=100, null=True)),
                ('officeCountry', models.CharField(blank=True, max_length=100, null=True)),
                ('officePostalCode', models.CharField(blank=True, max_length=7, null=True)),
                ('companyName', models.CharField(max_length=255)),
                ('designation', models.CharField(blank=True, max_length=256, null=True)),
                ('startDate', models.DateField(null=True)),
                ('endDate', models.DateField(null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+1 (XXX) XXX-XXXX", regex='^\\+?1?\\d{9,13}$')])),
                ('identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='smarteq.identity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passportNumber', models.CharField(blank=True, max_length=12, null=True)),
                ('placeOfIssue', models.CharField(blank=True, max_length=255, null=True)),
                ('countryIssued', models.CharField(blank=True, max_length=255, null=True)),
                ('dateOfIssue', models.DateField()),
                ('dateOfExpiry', models.DateField()),
                ('identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passport', to='smarteq.identity')),
            ],
        ),
        migrations.CreateModel(
            name='Socials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedIn', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('dice', models.URLField(blank=True, null=True)),
                ('monster', models.URLField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='smarteq.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gatedCountry', models.CharField(blank=True, max_length=256, null=True)),
                ('typeOfVisa', models.CharField(max_length=10)),
                ('dateOfIssue', models.DateField()),
                ('dateOfExpiry', models.DateField()),
                ('identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visa', to='smarteq.identity')),
                ('passport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smarteq.passport')),
            ],
        ),
        migrations.CreateModel(
            name='WorkAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeOfAuthorization', models.CharField(max_length=255)),
                ('dateOfValidity', models.DateField()),
                ('dateOfExpiry', models.DateField()),
                ('uscisNumber', models.CharField(max_length=100, unique=True)),
                ('cardNumber', models.CharField(max_length=255, unique=True)),
                ('identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employmentAuthorization', to='smarteq.identity')),
                ('visa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visa', to='smarteq.visa')),
            ],
        ),
    ]
