# Generated by Django 5.1.1 on 2024-10-05 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarteq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_1', models.CharField(blank=True, max_length=150, null=True)),
                ('street_2', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('postalCode', models.CharField(blank=True, max_length=7, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='officeCity',
        ),
        migrations.RemoveField(
            model_name='company',
            name='officeCountry',
        ),
        migrations.RemoveField(
            model_name='company',
            name='officePostalCode',
        ),
        migrations.RemoveField(
            model_name='company',
            name='officeState',
        ),
        migrations.RemoveField(
            model_name='company',
            name='officeStreet_1',
        ),
        migrations.RemoveField(
            model_name='company',
            name='officeStreet_2',
        ),
        migrations.RemoveField(
            model_name='education',
            name='primaryCity',
        ),
        migrations.RemoveField(
            model_name='education',
            name='primaryCountry',
        ),
        migrations.RemoveField(
            model_name='education',
            name='primaryPostalCode',
        ),
        migrations.RemoveField(
            model_name='education',
            name='primaryState',
        ),
        migrations.RemoveField(
            model_name='education',
            name='primaryStreet_1',
        ),
        migrations.RemoveField(
            model_name='education',
            name='primaryStreet_2',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='mailingCity',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='mailingCountry',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='mailingPostalCode',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='mailingState',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='mailingStreet_1',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='mailingStreet_2',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='primaryCity',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='primaryCountry',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='primaryPostalCode',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='primaryState',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='primaryStreet_1',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='primaryStreet_2',
        ),
        migrations.AddField(
            model_name='education',
            name='cityOfSchool',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='countryOfSchool',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='stateOfSchool',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='major',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='schoolName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workauthorization',
            name='identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workAuthorization', to='smarteq.identity'),
        ),
        migrations.AddField(
            model_name='company',
            name='officeAddress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='officeAddress', to='smarteq.address'),
        ),
        migrations.AddField(
            model_name='employee',
            name='mailingAddress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mailingAddress', to='smarteq.address'),
        ),
        migrations.AddField(
            model_name='employee',
            name='primaryAddress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primaryAddress', to='smarteq.address'),
        ),
    ]
