# Generated by Django 5.1.1 on 2024-09-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarteq', '0002_alter_employee_dateofbirth_alter_employee_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeparticulars',
            name='education',
        ),
        migrations.AddField(
            model_name='employeeparticulars',
            name='education',
            field=models.ManyToManyField(blank=True, null=True, to='smarteq.education'),
        ),
    ]
