# Generated by Django 5.1.1 on 2024-09-28 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarteq', '0004_alter_employee_primaryaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeparticulars',
            name='employmentAuthorization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smarteq.employmentauthorization'),
        ),
        migrations.AlterField(
            model_name='employeeparticulars',
            name='visa',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smarteq.visa'),
        ),
    ]
