# Generated by Django 5.1.1 on 2024-09-28 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarteq', '0005_alter_employeeparticulars_employmentauthorization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeparticulars',
            name='employmentAuthorization',
        ),
        migrations.AddField(
            model_name='employmentauthorization',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smarteq.employee'),
        ),
    ]
