# Generated by Django 5.1.1 on 2024-09-28 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarteq', '0007_alter_employmentauthorization_cardnumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeparticulars',
            name='employmentAuthorization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smarteq.employmentauthorization'),
        ),
    ]
