# Generated by Django 5.1.1 on 2024-09-29 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarteq', '0008_employeeparticulars_employmentauthorization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='location',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='socials',
        ),
        migrations.RemoveField(
            model_name='employeeparticulars',
            name='company',
        ),
        migrations.RemoveField(
            model_name='employeeparticulars',
            name='education',
        ),
        migrations.RemoveField(
            model_name='employeeparticulars',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeeparticulars',
            name='employmentAuthorization',
        ),
        migrations.RemoveField(
            model_name='employeeparticulars',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='employeeparticulars',
            name='passport',
        ),
        migrations.RemoveField(
            model_name='employeeparticulars',
            name='recruiter',
        ),
        migrations.RemoveField(
            model_name='employeeparticulars',
            name='visa',
        ),
        migrations.RemoveField(
            model_name='employmentauthorization',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='socials',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='socials',
        ),
        migrations.AddField(
            model_name='company',
            name='employeeParticulars',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smarteq.employeeparticulars'),
        ),
        migrations.AddField(
            model_name='education',
            name='employeeParticulars',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smarteq.employeeparticulars'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employeeParticulars',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smarteq.employeeparticulars'),
        ),
        migrations.AddField(
            model_name='employmentauthorization',
            name='employeeParticulars',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smarteq.employeeparticulars'),
        ),
        migrations.AddField(
            model_name='manager',
            name='employeeParticulars',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smarteq.employeeparticulars'),
        ),
        migrations.AddField(
            model_name='passport',
            name='employeeParticulars',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smarteq.employeeparticulars'),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='employeeParticulars',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smarteq.employeeparticulars'),
        ),
        migrations.AddField(
            model_name='socials',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smarteq.employee'),
        ),
        migrations.AddField(
            model_name='visa',
            name='employeeParticulars',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smarteq.employeeparticulars'),
        ),
        migrations.AddField(
            model_name='visa',
            name='passport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smarteq.passport'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mailingAddress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mailing_address', to='smarteq.address'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='officeAddress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='office_address', to='smarteq.address'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='primaryAddress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primaryAddress', to='smarteq.address'),
        ),
    ]
