# Generated by Django 5.1.1 on 2024-09-29 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarteq', '0009_remove_company_location_remove_employee_socials_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employeeParticulars',
        ),
        migrations.AddField(
            model_name='employeeparticulars',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smarteq.employee'),
        ),
    ]
