# Generated by Django 5.1.1 on 2024-09-29 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarteq', '0011_rename_postal_code_address_postalcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeparticulars',
            name='employee',
        ),
        migrations.AddField(
            model_name='employee',
            name='employeeParticulars',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smarteq.employeeparticulars'),
        ),
    ]
