# Generated by Django 5.1.1 on 2024-09-29 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarteq', '0012_remove_employeeparticulars_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='employeeParticulars',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smarteq.employeeparticulars', unique=True),
        ),
    ]
