# Generated by Django 5.1.1 on 2024-09-29 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarteq', '0014_alter_education_employeeparticulars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='employeeParticulars',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education', to='smarteq.employeeparticulars'),
        ),
        migrations.AlterField(
            model_name='employeeparticulars',
            name='socialSecurity',
            field=models.CharField(blank=True, default='XXX-XX-1234', max_length=5, null=True),
        ),
    ]
