# Generated by Django 5.1.1 on 2024-09-29 09:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarteq', '0015_alter_education_employeeparticulars_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employeeParticulars',
        ),
        migrations.AddField(
            model_name='employeeparticulars',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employeeParticulars', to='smarteq.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phoneNumber',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+18123603100", regex='^\\+?1?\\d{9,13}$')]),
        ),
        migrations.AlterField(
            model_name='employeeparticulars',
            name='socialSecurity',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='employmentauthorization',
            name='employeeParticulars',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employmentAuthorization', to='smarteq.employeeparticulars'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='employeeParticulars',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='smarteq.employeeparticulars'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='employeeParticulars',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passport', to='smarteq.employeeparticulars'),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='employeeParticulars',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruiter', to='smarteq.employeeparticulars'),
        ),
        migrations.AlterField(
            model_name='socials',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='smarteq.employee'),
        ),
        migrations.AlterField(
            model_name='visa',
            name='employeeParticulars',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visa', to='smarteq.employeeparticulars'),
        ),
    ]
