# Generated by Django 5.1.1 on 2024-09-29 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarteq', '0016_remove_employee_employeeparticulars_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeparticulars',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='smarteq.company'),
        ),
    ]
