# Generated by Django 5.1.1 on 2024-09-29 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarteq', '0017_alter_employeeparticulars_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeparticulars',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='smarteq.employee'),
        ),
    ]
