# Generated by Django 5.1.1 on 2024-09-29 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarteq', '0018_alter_employeeparticulars_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeparticulars',
            name='employee',
        ),
        migrations.AddField(
            model_name='employee',
            name='employeeParticulars',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='smarteq.employeeparticulars'),
        ),
    ]
