# Generated by Django 5.1.1 on 2024-09-29 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarteq', '0019_remove_employeeparticulars_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employmentauthorization',
            name='employeeParticulars',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='employeeParticulars',
        ),
        migrations.RemoveField(
            model_name='passport',
            name='employeeParticulars',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employeeParticulars',
        ),
        migrations.RemoveField(
            model_name='visa',
            name='employeeParticulars',
        ),
        migrations.RemoveField(
            model_name='education',
            name='employeeParticulars',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='employeeParticulars',
        ),
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smarteq.address'),
        ),
        migrations.AddField(
            model_name='education',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education', to='smarteq.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='smarteq.company'),
        ),
        migrations.AddField(
            model_name='employee',
            name='socialSecurity',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='employmentauthorization',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employmentAuthorization', to='smarteq.employee'),
        ),
        migrations.AddField(
            model_name='manager',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='smarteq.employee'),
        ),
        migrations.AddField(
            model_name='passport',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passport', to='smarteq.employee'),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruiter', to='smarteq.employee'),
        ),
        migrations.AddField(
            model_name='visa',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visa', to='smarteq.employee'),
        ),
        migrations.DeleteModel(
            name='EmployeeParticulars',
        ),
    ]
